#!/bin/bash -ex

destdir="$1"

cp -p ${BUILD_SCRIPTS}/pkg-xctools/utilities.sh ${destdir}
cp -p ${BUILD_SCRIPTS}/pkg-xctools/install.sh ${destdir}
cp -p ${BUILD_SCRIPTS}/pkg-xctools/README ${destdir}
cp -p ${BUILD_SCRIPTS}/pkg-xctools/fix-i915-passthrough.sh ${destdir}
cp -p ${BUILD_SCRIPTS}/pkg-xctools/xc-i915-passthrough.patch  ${destdir}
cp -p ${BUILD_SCRIPTS}/pkg-xctools/dkms-*.rpm  ${destdir}
