#!/bin/sh

set +e

if [ -r /etc/redhat-release ] ; then
    DISTRO=rhel
else
    DISTRO=debian
fi

if [ -e "`which xenstore-write`" -a -e "`which xenstore-exists`" ]; then
    xenstore-exists attr || xenstore-write "attr"
    xenstore-exists "attr/PVAddons" || xenstore-write "attr/PVAddons" ""
    xenstore-write "attr/PVAddons/Installed"  "0"
    xenstore-write "attr/PVAddonsUninstalled" "1"
fi

RUN_ONCE_SH="/usr/src/xenstore-agent-1.0/run-one-time.sh"
[ -f "${RUN_ONCE_SH}" ] && rm -f ${RUN_ONCE_SH}

if [ "$DISTRO" = rhel ] ; then
    DKMS_RPM_SAFE="--rpm_safe_upgrade"
else
    DKMS_RPM_SAFE=
fi

for PVD in "v4v" "xenmou" "vusb"
do
    NAME=openxt-${PVD}
    PACKAGE=${NAME}-dkms
    VERSION=1.0
    SRCS=/usr/src/${PACKAGE}-${VERSION}

    dkms_status="$(dkms status -m openxt-$mod)"
    dkms_state="${dkms_status##*: }"
    if [ -n "${dkms_state}" ]; then
        dkms remove -m ${PACKAGE} -v ${VERSION} --all ${DKMS_RPM_SAFE}
    fi
done


if [ "${DISTRO}" = rhel ] ; then
    chkconfig --del xenstore-agent
    chkconfig --del xblanker
fi

exit 0
