#!/bin/sh
#
# xblanker
#
# chkconfig:   2345 76 24
# description: xblanker

### BEGIN INIT INFO
# Provides: xblanker
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Should-Start:
# Should-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: xblanker
# Description: xblanker
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

daemon=/usr/local/bin/xblanker
prog=`basename $daemon`

lockfile=/var/lock/subsys/$prog

load_modules() {
    echo -n $"Loading kernel modules for $prog: "

    if ! modprobe xc-xenfs ; then
        failure
        echo
        exit 1
    fi

    success
    echo
}

mount_xenfs() {
    echo -n $"Mounting /proc/xen: "
    mount -t xenfs nodev /proc/xen 2>/dev/null

    success
    echo
}

start_xblanker() {
    # TODO: update xblanker to run as a daemon
    echo -n $"Starting $prog: "
    
    if ! daemon $daemon "</dev/null" ">&0" "2>&1" "&" ; then
        failure
        echo
        exit 1
    fi

    success
    echo
}

stop_xblanker() {
    echo -n $"Stopping $prog: "
    if ! killproc $prog ; then
        failure
        echo
        exit 1
    fi

    success
    echo
}

start() {
    load_modules
    mount_xenfs
    start_xblanker

    touch $lockfile
}

stop() {
    stop_xblanker

    rm -f $lockfile
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

status_q() {
    status $prog >/dev/null 2>&1
}


case "$1" in
    start)
        status_q && exit 0
        $1
        ;;
    stop)
        status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        status $prog
        ;;
    condrestart|try-restart)
        status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit 0
